name: workflow
on: 
  - push
  - workflow_dispatch
jobs:
  
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: acknowledge
        run: echo "push has been completed"

  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: create pull request to merge changes to main
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          get_diff: true
          title: pull request from workflow

        